trigger:
  branches:
    include:
    - '*'

stages:

- stage: 'preparationStage'
  jobs:
  - job: 'job'
    steps:
    - task: 'PowerShell@2'
      name: 'determineVersion'
      inputs:
        targetType: 'inline'
        pwsh: true
        script: |
          Write-Host "##vso[task.setvariable variable=releaseChannel;isOutput=true]value"

- stage: 'Stage'
  variables:
  - name: 'releaseChannel'
    value: $[ stageDependencies.preparationStage.job.outputs['determineVersion.releaseChannel'] ]
  jobs:
  - job: 'Job'
    steps:
    - template: 'template.yml'
      parameters:
        createDistribution: true
