parameters:

- name: 'makeNightlyBuild'
  displayName: 'Make nightly build'
  type: 'boolean'
  default: 'false'

trigger:
  batch: 'true'
  branches:
    include:
    - master
    - publish/*
    - development/*
    - release/*
    - feature/*
    - bugfix/*
  tags:
    include:
    - publish/*
    - build/*

variables:
  var1: 'jon'
  var2: $(var1)

stages:

- stage: 'Stage'
  condition: succeeded()
  jobs:
  - job: 'Job'
    steps:

    - checkout: self
      persistCredentials: 'true'

    - task: 'PowerShell@2'
      inputs:
        targetType: 'inline'
        pwsh: true
        failOnStderr: true
        ignoreLASTEXITCODE: true
        script: |
          $var2 = '${{ variables.var2 }}'
          Write-Host $var2

    # - template: 'template.yml'
    #   parameters:
    #     createDistribution: true
    #     releaseChannel: $(releaseChannel)
